### ISSUE TITLE
loss in train process

### ISSUE THREAD

**Issue by lehy786** [zhxl0903/CSCD94_VESPCN#3]
Hi, thank you for sharing the code firstly. **It was my first time to run a deep learning program**. I've followed the guide and tried to run this project. And I found the training process was like:
Epoch:  1  Step:  20    Loss:  0.62372065
Epoch:  1  Step:  20    Loss:  0.4303338
Epoch:  1  Step:  30    Loss:  0.31553578
Epoch:  1  Step:  40    Loss:  0.24472743
Epoch:  2  Step:  50   Loss:  0.19411418
Epoch:  2  Step:  60    Loss:  0.15059762
Epoch:  2  Step:  70    Loss:  0.12363284
Epoch:  2  Step:  80    Loss:  0.09769744
Epoch:  2  Step:  90    Loss:  0.08767132
Epoch:  3  Step:  100    Loss:  0.074898556
Epoch:  3  Step:  110    Loss:  0.057604786
Epoch:  3  Step:  120    Loss:  0.05190464
Epoch:  3  Step:  130    Loss:  0.037110887
Epoch:  3  Step:  140    Loss:  0.03755188
Epoch:  4  Step:  150    Loss:  0.033167027
Epoch:  4  Step:  160    Loss:  0.025966365
Epoch:  4  Step:  170    Loss:  0.023781314
Epoch:  4  Step:  180    Loss:  0.021020738
Epoch:  4  Step:  190    Loss:  0.017251965
Epoch:  5  Step:  200    Loss:  0.016756233
Epoch:  5  Step:  210    Loss:  0.01717031
Epoch:  5  Step:  220    Loss:  0.015247038
Epoch:  5  Step:  230    Loss:  0.013656748
Epoch:  5  Step:  240    Loss:  0.013235073
Epoch:  6  Step:  250    Loss:  0.011337386
Epoch:  6  Step:  260    Loss:  0.011241261
Epoch:  6  Step:  270    Loss:  0.009624703
Epoch:  6  Step:  280    Loss:  0.0120983245
Epoch:  6  Step:  290    Loss:  0.0098843835
Epoch:  7  Step:  300    Loss:  0.009633852
Epoch:  7  Step:  310    Loss:  0.008983937
Epoch:  7  Step:  320    Loss:  0.009625918

the loss seems falling so fast? Or it‘s just the normal phenomenon at image reconstruction? Thanks  a lot!

**Comment by zhxl0903** [comment]
Hi, thanks for paying attention!

This looks normal for a small dataset. A bigger dataset may be needed to achieve 
better final SR performance.

Thanks!
zhxl0903
