### ISSUE TITLE
合适的数据集大小

### ISSUE THREAD

**Issue by lehy786** [zhxl0903/CSCD94_VESPCN#4]
您好，我想请问，像这类方法做重建的，数据集的大小一般要求在多少合适？我现在正在制作自己的数据集，但是不知道训练集规模定为多少算合适，希望您能解答一下，谢谢。

**Comment by zhxl0903** [comment]
Hello, thanks for paying attention!

The paper uses 115 uncompressed full HD videos with 30 samples extracted from each video, where each sample is a block of consecutive frames. 100 videos are used for training and 15 videos are used for testing. The video samples are are further broken down into subsamples and grouped in batches for training. 

We've experimented with 30 videos of the above configuration with 25 for training and 5 for testing and the performance is roughly similar to that of the paper.

Thanks!
zhxl0903

**Comment by lehy786** [comment]
Thank you so much!!
